-- Distritos de Lima
INSERT INTO distrito(nombre_distrito) VALUES ('Ancón');
INSERT INTO distrito(nombre_distrito) VALUES ('Puente Piedra');
INSERT INTO distrito(nombre_distrito) VALUES ('Santa Rosa');
INSERT INTO distrito(nombre_distrito) VALUES ('Carabayllo');
INSERT INTO distrito(nombre_distrito) VALUES ('Comas');
INSERT INTO distrito(nombre_distrito) VALUES ('Los Olivos');
INSERT INTO distrito(nombre_distrito) VALUES ('Independencia');
INSERT INTO distrito(nombre_distrito) VALUES ('San Martín de Porres');
INSERT INTO distrito(nombre_distrito) VALUES ('San Juan de Lurigancho');
INSERT INTO distrito(nombre_distrito) VALUES ('Santa Anita');
INSERT INTO distrito(nombre_distrito) VALUES ('Cieneguilla');
INSERT INTO distrito(nombre_distrito) VALUES ('Ate Vitarte');
INSERT INTO distrito(nombre_distrito) VALUES ('La Molina');
INSERT INTO distrito(nombre_distrito) VALUES ('Chaclacayo');
INSERT INTO distrito(nombre_distrito) VALUES ('Lurigancho');
INSERT INTO distrito(nombre_distrito) VALUES ('El Agustino');
INSERT INTO distrito(nombre_distrito) VALUES ('San Juan de Miraflores');
INSERT INTO distrito(nombre_distrito) VALUES ('Villa María del Triunfo');
INSERT INTO distrito(nombre_distrito) VALUES ('Villa El Salvador');
INSERT INTO distrito(nombre_distrito) VALUES ('Lurín');
INSERT INTO distrito(nombre_distrito) VALUES ('Pachacámac');
INSERT INTO distrito(nombre_distrito) VALUES ('Punta Hermosa');
INSERT INTO distrito(nombre_distrito) VALUES ('Pucusana');
INSERT INTO distrito(nombre_distrito) VALUES ('Punta Negra');
INSERT INTO distrito(nombre_distrito) VALUES ('San Bartolo');
INSERT INTO distrito(nombre_distrito) VALUES ('Santa María');
INSERT INTO distrito(nombre_distrito) VALUES ('Provincia');